-- Migration 008: Create actions table
-- User task queue — generated by the Action Generator agent.
-- Each action links to an opportunity (and optionally a contact, company, signal).

CREATE TABLE IF NOT EXISTS actions (
    id                  uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id             uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    opportunity_id      uuid REFERENCES opportunities(id) ON DELETE SET NULL,
    company_id          uuid REFERENCES companies(id) ON DELETE SET NULL,
    contact_id          uuid REFERENCES contacts(id) ON DELETE SET NULL,
    title               text NOT NULL,
    description         text,
    type                text NOT NULL,              -- OUTREACH|FOLLOW_UP|RESEARCH|CALL
    priority            text NOT NULL DEFAULT 'MEDIUM', -- HIGH|MEDIUM|LOW
    status              text NOT NULL DEFAULT 'TODO',   -- TODO|IN_PROGRESS|DONE|SNOOZED
    due_date            timestamptz,
    source_signal_id    uuid REFERENCES signals(id) ON DELETE SET NULL,
    ai_draft_json       jsonb NOT NULL DEFAULT '{}',
    created_at          timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE actions IS 'Prioritized task queue for the user — generated by Action Generator agent.';
COMMENT ON COLUMN actions.type IS 'Action category: OUTREACH|FOLLOW_UP|RESEARCH|CALL';
COMMENT ON COLUMN actions.priority IS 'Priority band: HIGH|MEDIUM|LOW — computed from urgency × confidence × fit_score.';
COMMENT ON COLUMN actions.ai_draft_json IS 'Pre-computed AI draft payload (e.g., email draft) attached to this action.';
